import React from "react";
import Head from "next/head";

const about = () => {
	return (
		<div>
			<Head>
				<title>About us</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<meta
					property="og:image"
					content="https://st2.depositphotos.com/3591429/10566/i/600/depositphotos_105666254-stock-photo-business-people-at-meeting-and.jpg"
				/>
			</Head>
			<h1>About us</h1>
		</div>
	);
};

export default about;
